//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unisync.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class APUNTE
    {
        public int ID_APUNTE { get; set; }
        public string CONTENIDO { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public string ETIQUETA { get; set; }
        public Nullable<int> ID_ASIGNATURA { get; set; }
    
        public virtual ASIGNATURA ASIGNATURA { get; set; }
    }
}
