//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unisync.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CALIFICACION
    {
        public int ID_CALIFICACION { get; set; }
        public double NOTA { get; set; }
        public double PORCENTAJE { get; set; }
        public Nullable<int> ID_ASIGNATURA { get; set; }
    
        public virtual ASIGNATURA ASIGNATURA { get; set; }
    }
}
