//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unisync.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HORARIO
    {
        public int ID_HORARIO { get; set; }
        public Nullable<System.TimeSpan> HORA_INICIO { get; set; }
        public Nullable<System.TimeSpan> HORA_FIN { get; set; }
        public string DIAS { get; set; }
        public Nullable<bool> NOTIFICACION { get; set; }
        public Nullable<int> ID_ASIGNATURA { get; set; }
    
        public virtual ASIGNATURA ASIGNATURA { get; set; }
    }
}
