//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unisync.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAREA
    {
        public int ID_TAREA { get; set; }
        public string NOMBRE { get; set; }
        public string DESCRIPCION { get; set; }
        public System.DateTime FECHA_ENTREGA { get; set; }
        public bool PRIORIDAD { get; set; }
        public bool ESTADO { get; set; }
        public Nullable<bool> NOTIFICACION { get; set; }
        public Nullable<int> ID_ASIGNATURA { get; set; }
    
        public virtual ASIGNATURA ASIGNATURA { get; set; }
    }
}
