//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unisync.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UNISYNCEntities1 : DbContext
    {
        public UNISYNCEntities1()
            : base("name=UNISYNCEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<APUNTE> APUNTEs { get; set; }
        public virtual DbSet<ASIGNATURA> ASIGNATURAs { get; set; }
        public virtual DbSet<CALIFICACION> CALIFICACIONs { get; set; }
        public virtual DbSet<HORARIO> HORARIOs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TAREA> TAREAs { get; set; }
        public virtual DbSet<USUARIO> USUARIOs { get; set; }
    }
}
